"""bloodoath model

Revision ID: 6700b8b1346f
Revises: 95df60fee3d1
Create Date: 2023-07-14 19:20:12.405274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6700b8b1346f'
down_revision = '95df60fee3d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_oaths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiation_date', sa.String(), nullable=True),
    sa.Column('cult_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blood_oaths')
    # ### end Alembic commands ###
