"""follower model

Revision ID: 95df60fee3d1
Revises: 74f6667e69e2
Create Date: 2023-07-14 19:18:30.419875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95df60fee3d1'
down_revision = '74f6667e69e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('life_motto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
