"""added minimum age to Cult

Revision ID: a143444b9832
Revises: e9884056b907
Create Date: 2023-07-16 19:34:09.816517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a143444b9832'
down_revision = 'e9884056b907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cults', sa.Column('minimum_age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cults', 'minimum_age')
    # ### end Alembic commands ###
